task default: %i[
       clean
       prepare
       build_plugin
       download
       extract_locale
       extract_effects
       list_effects
     ]

ENABLE_EXTRACTION_KEY = "DANGEROUSLY_ENABLE_EXTRACTION"
ENABLE_EXTRACTION = ENV["CI"] || (ENV[ENABLE_EXTRACTION_KEY] == "1")

task :clean do
  rm_rf "tmp/aviutl2"
  rm_rf "tmp/aviutl2.zip"
  puts "Cleaned up temporary files."
end
task :prepare do
  mkdir_p "tmp"
  File.write("tmp/.gitignore", "*\n")
  puts "Prepared temporary directory."
end

task :build_plugin do
  sh "cmake -S . -B build -D CMAKE_BUILD_TYPE=Release", chdir: "./plugin"
  sh "cmake --build build --config Release", chdir: "./plugin"
end

task :download do
  require "open-uri"
  require "zip"

  html_url = "https://spring-fragrance.mints.ne.jp/aviutl/"
  html_content = URI.open(html_url).read
  zip_filename = html_content.match(/<A HREF="(aviutl2beta[0-9a-z]+\.zip)">/)[1]
  zip_url = html_url + zip_filename
  zip_path = "tmp/aviutl2.zip"
  puts "Downloading #{zip_url}..."
  URI.open(zip_url) do |remote_file|
    File.open(zip_path, "wb") { |file| file.write(remote_file.read) }
  end
  puts "Downloaded to #{zip_path}."

  installer_path = "tmp/aviutl2_setup.exe"
  installer_filename =
    html_content.match(/<A HREF="(AviUtl2beta[0-9a-z]+_setup\.exe)">/)[1]
  installer_url = html_url + installer_filename
  puts "Downloading installer #{installer_url}..."
  URI.open(installer_url) do |remote_file|
    File.open(installer_path, "wb") { |file| file.write(remote_file.read) }
  end
  puts "Downloaded installer to #{installer_path}."

  Zip::File.open(zip_path) do |zip_file|
    zip_file.each do |entry|
      dest_path = File.join("tmp", "aviutl2", entry.name)
      mkdir_p File.dirname(dest_path) unless Dir.exist?(File.dirname(dest_path))
      zip_file.extract(entry, dest_path) unless File.exist?(dest_path)
    end
  end
  puts "Extracted ZIP to tmp/aviutl2."
end

task :extract_locale do
  require "open3"
  require "fileutils"

  puts "Extracting locale data..."
  data_dir = "C:/ProgramData/aviutl2"
  eng_path = "#{data_dir}/Language/English.aul2"

  if File.exist?(eng_path)
    puts "Locale data already exists at #{eng_path}."
  else
    puts "Running AviUtl2 installer to extract locale data..."
    unless ENABLE_EXTRACTION
      puts "Locale extraction is disabled. Set #{ENABLE_EXTRACTION_KEY}=1 to enable."
      next
    end
    installer_path = "tmp/aviutl2_setup.exe"
    sh "#{installer_path} /SILENT /DIR=\"#{File.expand_path("tmp/aviutl2_installer")}\""
  end

  cp eng_path, "../locales/original_english.aul2"
end

task :extract_effects do
  require "open3"
  puts "Extracting effects..."

  rm_rf "./tmp/aviutl2/data"
  mkdir_p "./tmp/aviutl2/data/Plugin"
  cp "./plugin/build/Release/ExtractPlugin.dll",
     "./tmp/aviutl2/data/Plugin/ExtractPlugin.aux2"
  mkdir_p "./tmp/aviutl2/data/extract"

  mode_path = "./tmp/aviutl2/data/extract/mode.txt"
  File.write(mode_path, "extract")

  puts "Trusting ExtractPlugin.aux2 for effect extraction."
  File.write("./tmp/aviutl2/data/module.ini", <<~INI)
    [ExtractPlugin.aux2]
    trust=1
  INI
  puts "Launching AviUtl2 to extract effects..."

  current_time = Time.now
  spawn("tmp/aviutl2/AviUtl2.exe")
  while Time.now - current_time < 60
    sleep 1
    unless File.exist?(mode_path)
      puts "Effect extraction completed."
      break
    end
  end

  rm_rf "./tmp/extracted_effects"
  cp_r "./tmp/aviutl2/data/extract/effects", "./tmp/extracted_effects"
end

task :list_effects do
  require "json"
  require "inifile"
  puts "Listing extracted effects..."
  effects_dir = "./tmp/extracted_effects"
  effects =
    Dir
      .glob("#{effects_dir}/*.object")
      .to_h do |path|
        ini = IniFile.load(path)
        object_0 = ini["Object.0"].to_h
        effect_name = object_0.delete("effect.name")
        object_0.delete("Group") # TODO: なにこれ
        [effect_name, object_0.keys]
      end

  File.write("./effects.json", JSON.pretty_generate(effects) + "\n")
  puts "Wrote effects list to ./tmp/effects.json."
end

task :upload do
  require "http"
  require "dotenv/load"
  require "inifile"

  puts "Uploading translations"
  keys = []
  main_translations = IniFile.load("../locales/original_english.aul2")
  main_translations.each do |section, key, value|
    # valueは完全に無視する
    keys << {
      name: key,
      namespace: "editor.#{section}",
      translations: {
        ja: key
      }
    }
  end
  effects = JSON.parse(File.read("./effects.json"))
  effects.each do |effect_name, effect_keys|
    keys << {
      name: effect_name,
      namespace: "effect.#{effect_name}",
      translations: {
        ja: effect_name
      }
    }
    effect_keys.each do |key|
      keys << {
        name: key,
        namespace: "effect.#{effect_name}",
        translations: {
          ja: key
        }
      }
    end
  end

  raise "TODO: ホスト先を決める"
end
